import type { Member } from './utils';
import { ROLE_IDS } from './roleIds';

export const MEMBERS: readonly Member[] = [
  {
    github: '000-000-000-000-000',
    discord: '1360717264051241071',
    firstName: 'Nick',
    lastName: 'Aldridge',
    googleEmailPrefix: 'nick',
    memberOf: [ROLE_IDS.CORE_MAINTAINERS],
  },
  {
    github: 'a-akimov',
    discord: '1365254196621738116',
    memberOf: [ROLE_IDS.DOCS_MAINTAINERS],
  },
  {
    github: 'aaronpk',
    discord: '324624369428987905',
    memberOf: [ROLE_IDS.AUTH_MAINTAINERS, ROLE_IDS.MAINTAINERS],
  },
  {
    github: 'alexhancock',
    discord: '1325885093343924316',
    memberOf: [ROLE_IDS.RUST_SDK],
  },
  {
    github: 'an-dustin',
    memberOf: [ROLE_IDS.SECURITY_WG],
  },
  {
    github: 'antonpk1',
    discord: '738474760480227358',
    memberOf: [ROLE_IDS.MCP_APPS_SDK],
  },
  {
    github: 'asklar',
    discord: '633837375734153216',
    memberOf: [ROLE_IDS.MCPB_MAINTAINERS],
  },
  {
    github: 'atesgoral',
    discord: '201179934775836672',
    memberOf: [ROLE_IDS.RUBY_SDK],
  },
  {
    github: 'baxen',
    discord: '360224027769307136',
    memberOf: [ROLE_IDS.RUST_SDK],
  },
  {
    github: 'bhosmer-ant',
    discord: '1272295077074567242',
    memberOf: [
      ROLE_IDS.DOCS_MAINTAINERS,
      ROLE_IDS.MODERATORS,
      ROLE_IDS.PYTHON_SDK,
      ROLE_IDS.TYPESCRIPT_SDK,
    ],
  },
  {
    github: 'BobDickinson',
    email: 'bob.dickinson@gmail.com',
    discord: '1175893001202045139',
    skipGoogleUserProvisioning: true,
    memberOf: [
      ROLE_IDS.MAINTAINERS,
      ROLE_IDS.INSPECTOR_MAINTAINERS,
      ROLE_IDS.REGISTRY_MAINTAINERS,
      ROLE_IDS.SKILLS_OVER_MCP_IG,
    ],
  },
  {
    github: 'bolinfest',
    memberOf: [ROLE_IDS.RUST_SDK],
  },
  {
    github: 'caitiem20',
    email: 'caitie.mccaffrey@microsoft.com',
    discord: '1425586366288494722',
    firstName: 'Caitie',
    lastName: 'McCaffrey',
    googleEmailPrefix: 'caitie',
    memberOf: [ROLE_IDS.CORE_MAINTAINERS, ROLE_IDS.TRANSPORT_WG],
  },
  {
    github: 'chemicL',
    discord: '1346243721271971923',
    memberOf: [ROLE_IDS.JAVA_SDK],
  },
  {
    github: 'chr-hertel',
    email: 'mail@christopher-hertel.de',
    discord: '633566986827464704',
    memberOf: [ROLE_IDS.PHP_SDK],
  },
  {
    github: 'chughtapan',
    email: 'chugh.tapan@gmail.com',
    discord: '941245973357793340',
    memberOf: [
      ROLE_IDS.MAINTAINERS,
      ROLE_IDS.INTEREST_GROUPS,
      ROLE_IDS.PRIMITIVE_GROUPING_IG,
      ROLE_IDS.WG_IG_FACILITATORS,
    ],
  },
  {
    github: 'cliffhall',
    email: 'cliff@futurescale.com',
    discord: '501498061965754380',
    firstName: 'Cliff',
    lastName: 'Hall',
    googleEmailPrefix: 'cliff',
    existingGWSUser: true,
    memberOf: [
      ROLE_IDS.COMMUNITY_MANAGERS,
      ROLE_IDS.MAINTAINERS,
      ROLE_IDS.DOCS_MAINTAINERS,
      ROLE_IDS.INSPECTOR_MAINTAINERS,
      ROLE_IDS.PRIMITIVE_GROUPING_IG,
      ROLE_IDS.REFERENCE_SERVERS_MAINTAINERS,
      ROLE_IDS.MODERATORS,
      ROLE_IDS.SKILLS_OVER_MCP_IG,
      ROLE_IDS.WORKING_GROUPS,
    ],
  },
  {
    github: 'CodeWithKyrian',
    discord: '951883230250946633',
    memberOf: [ROLE_IDS.PHP_SDK],
  },
  {
    github: 'crondinini-ant',
    memberOf: [],
  },
  {
    github: 'D-McAdams',
    discord: '1364696680980545697',
    memberOf: [ROLE_IDS.AUTH_MAINTAINERS],
  },
  {
    github: 'daleseo',
    discord: '267646459187298305',
    memberOf: [ROLE_IDS.RUST_SDK],
  },
  {
    github: 'dend',
    skipGoogleUserProvisioning: true,
    memberOf: [
      ROLE_IDS.AUTH_MAINTAINERS,
      ROLE_IDS.CORE_MAINTAINERS,
      ROLE_IDS.DOCS_MAINTAINERS,
      ROLE_IDS.CSHARP_SDK_ADMIN,
      ROLE_IDS.ADMINISTRATORS,
      ROLE_IDS.GO_SDK,
      ROLE_IDS.FINANCIAL_SERVICES_IG,
      ROLE_IDS.MODERATORS,
      ROLE_IDS.PHP_SDK,
      ROLE_IDS.PYTHON_SDK,
      ROLE_IDS.SECURITY_WG,
      ROLE_IDS.TRANSPORT_WG,
      ROLE_IDS.TYPESCRIPT_SDK,
    ],
  },
  {
    github: 'devcrocod',
    memberOf: [ROLE_IDS.KOTLIN_SDK],
  },
  {
    github: 'domdomegg',
    email: 'adam@modelcontextprotocol.io',
    discord: '102128241715716096',
    firstName: 'Adam',
    lastName: 'Jones',
    googleEmailPrefix: 'adam',
    existingGWSUser: true,
    memberOf: [ROLE_IDS.MCPB_MAINTAINERS, ROLE_IDS.REGISTRY_MAINTAINERS],
  },
  {
    github: 'dsp',
    skipGoogleUserProvisioning: true,
    memberOf: [
      ROLE_IDS.AUTH_MAINTAINERS,
      ROLE_IDS.LEAD_MAINTAINERS,
      ROLE_IDS.CORE_MAINTAINERS,
      ROLE_IDS.DOCS_MAINTAINERS,
      ROLE_IDS.GO_SDK,
      ROLE_IDS.FINANCIAL_SERVICES_IG,
      ROLE_IDS.MODERATORS,
      ROLE_IDS.PHP_SDK,
      ROLE_IDS.PYTHON_SDK,
      ROLE_IDS.SECURITY_WG,
      ROLE_IDS.TRANSPORT_WG,
      ROLE_IDS.TYPESCRIPT_SDK,
    ],
  },
  {
    github: 'dsp-ant',
    email: 'david@modelcontextprotocol.io',
    discord: '166107790262272000',
    firstName: 'David',
    lastName: 'Soria Parra',
    googleEmailPrefix: 'david',
    existingGWSUser: true,
    memberOf: [
      ROLE_IDS.AUTH_MAINTAINERS,
      ROLE_IDS.LEAD_MAINTAINERS,
      ROLE_IDS.CORE_MAINTAINERS,
      ROLE_IDS.DOCS_MAINTAINERS,
      ROLE_IDS.MODERATORS,
    ],
  },
  {
    github: 'e5l',
    memberOf: [ROLE_IDS.KOTLIN_SDK],
  },
  {
    github: 'eiriktsarpalis',
    memberOf: [ROLE_IDS.CSHARP_SDK],
  },
  {
    github: 'EmLauber',
    discord: '1408222390361657426',
    memberOf: [ROLE_IDS.WG_IG_FACILITATORS],
  },
  {
    github: 'erain',
    discord: '797226095874539539',
    memberOf: [ROLE_IDS.SKILLS_OVER_MCP_IG],
  },
  {
    github: 'ericstj',
    memberOf: [ROLE_IDS.CSHARP_SDK],
  },
  {
    github: 'evalstate',
    discord: '779268016121577492',
    firstName: 'Shaun',
    lastName: 'Smith',
    googleEmailPrefix: 'shaun.smith',
    memberOf: [
      ROLE_IDS.COMMUNITY_MANAGERS,
      ROLE_IDS.DOCS_MAINTAINERS,
      ROLE_IDS.MAINTAINERS,
      ROLE_IDS.MODERATORS,
    ],
  },
  {
    github: 'fabpot',
    memberOf: [ROLE_IDS.PHP_SDK],
  },
  {
    github: 'felixrieseberg',
    memberOf: [ROLE_IDS.MCPB_MAINTAINERS],
  },
  {
    github: 'felixweinberger',
    discord: '1377138523492057212',
    memberOf: [ROLE_IDS.PYTHON_SDK, ROLE_IDS.SECURITY_WG, ROLE_IDS.TYPESCRIPT_SDK],
  },
  {
    github: 'findleyr',
    discord: '776094836796424213',
    memberOf: [ROLE_IDS.GO_SDK],
  },
  {
    github: 'halter73',
    memberOf: [ROLE_IDS.CSHARP_SDK, ROLE_IDS.CSHARP_SDK_ADMIN],
  },
  {
    github: 'herczyn',
    discord: '1001427188068917279',
    memberOf: [ROLE_IDS.GO_SDK],
  },
  {
    github: 'idosal',
    discord: '593070927202484244',
    memberOf: [ROLE_IDS.WORKING_GROUPS, ROLE_IDS.MCP_APPS_WG, ROLE_IDS.MCP_APPS_SDK],
  },
  {
    github: 'ignatov',
    memberOf: [ROLE_IDS.KOTLIN_SDK],
  },
  {
    github: 'ihrpr',
    memberOf: [ROLE_IDS.DOCS_MAINTAINERS, ROLE_IDS.PYTHON_SDK, ROLE_IDS.TYPESCRIPT_SDK],
  },
  {
    github: 'jamadeo',
    memberOf: [ROLE_IDS.RUST_SDK],
  },
  {
    github: 'JAORMX',
    discord: '1185152774674055193',
    memberOf: [ROLE_IDS.SKILLS_OVER_MCP_IG],
  },
  {
    github: 'jba',
    discord: '773276903364755518',
    memberOf: [ROLE_IDS.GO_SDK],
  },
  {
    github: 'jeffhandley',
    memberOf: [ROLE_IDS.CSHARP_SDK, ROLE_IDS.CSHARP_SDK_ADMIN],
  },
  {
    github: 'jenn-newton',
    memberOf: [ROLE_IDS.SECURITY_WG],
  },
  {
    github: 'jerome3o-anthropic',
    discord: '222246825397059585',
    memberOf: [ROLE_IDS.MODERATORS],
  },
  {
    github: 'joan-anthropic',
    discord: '1398403578892128437',
    memberOf: [ROLE_IDS.MCPB_MAINTAINERS],
  },
  {
    github: 'jokemanfire',
    memberOf: [ROLE_IDS.RUST_SDK],
  },
  {
    github: 'jonathanhefner',
    discord: '1301960963087663186',
    memberOf: [
      ROLE_IDS.COMMUNITY_MANAGERS,
      ROLE_IDS.DOCS_MAINTAINERS,
      ROLE_IDS.MAINTAINERS,
      ROLE_IDS.MODERATORS,
      ROLE_IDS.RUBY_SDK,
      ROLE_IDS.MCP_APPS_SDK,
    ],
  },
  {
    github: 'jozkee',
    memberOf: [ROLE_IDS.CSHARP_SDK],
  },
  {
    github: 'jspahrsummers',
    email: 'justin@modelcontextprotocol.io',
    firstName: 'Justin',
    lastName: 'Spahr-Summers',
    googleEmailPrefix: 'justin',
    existingGWSUser: true,
    memberOf: [ROLE_IDS.LEAD_MAINTAINERS, ROLE_IDS.CORE_MAINTAINERS],
  },
  {
    github: 'kaxil',
    discord: '757355088946921474',
    memberOf: [ROLE_IDS.SKILLS_OVER_MCP_IG],
  },
  {
    github: 'Kehrlann',
    discord: '1112624611901837373',
    memberOf: [ROLE_IDS.JAVA_SDK],
  },
  {
    github: 'keithagroves',
    discord: '321019863260987392',
    memberOf: [ROLE_IDS.SKILLS_OVER_MCP_IG],
  },
  {
    github: 'KKonstantinov',
    discord: '390932438903422987',
    memberOf: [ROLE_IDS.INSPECTOR_MAINTAINERS, ROLE_IDS.MAINTAINERS, ROLE_IDS.TYPESCRIPT_SDK],
    firstName: 'Konstantin',
    lastName: 'Konstantinov',
    googleEmailPrefix: 'konstantin',
  },
  {
    github: 'Kludex',
    discord: '247021664624312322',
    memberOf: [ROLE_IDS.PYTHON_SDK],
  },
  {
    github: 'koic',
    discord: '880937364208361483',
    memberOf: [ROLE_IDS.RUBY_SDK],
  },
  {
    github: 'kpavlov',
    memberOf: [ROLE_IDS.KOTLIN_SDK],
  },
  {
    github: 'kurtisvg',
    discord: '1158458388917780590',
    skipGoogleUserProvisioning: true,
    memberOf: [ROLE_IDS.CORE_MAINTAINERS, ROLE_IDS.TRANSPORT_WG],
  },
  {
    github: 'liady',
    discord: '383565833768665088',
    memberOf: [ROLE_IDS.WORKING_GROUPS, ROLE_IDS.MCP_APPS_WG, ROLE_IDS.MCP_APPS_SDK],
  },
  {
    github: 'localden',
    discord: '1351224014143754260',
    firstName: 'Den',
    lastName: 'Delimarsky',
    googleEmailPrefix: 'den',
    existingGWSUser: true,
    memberOf: [
      ROLE_IDS.AUTH_MAINTAINERS,
      ROLE_IDS.CORE_MAINTAINERS,
      ROLE_IDS.DOCS_MAINTAINERS,
      ROLE_IDS.CSHARP_SDK_ADMIN,
      ROLE_IDS.ADMINISTRATORS,
      ROLE_IDS.GO_SDK,
      ROLE_IDS.FINANCIAL_SERVICES_IG,
      ROLE_IDS.MODERATORS,
      ROLE_IDS.PHP_SDK,
      ROLE_IDS.PYTHON_SDK,
      ROLE_IDS.SECURITY_WG,
      ROLE_IDS.TRANSPORT_WG,
      ROLE_IDS.TYPESCRIPT_SDK,
    ],
  },
  {
    github: 'LucaButBoring',
    discord: '1366470072729866252',
    firstName: 'Luca',
    lastName: 'Chang',
    googleEmailPrefix: 'luca',
    memberOf: [ROLE_IDS.MAINTAINERS, ROLE_IDS.AGENTS_IG, ROLE_IDS.WORKING_GROUPS],
  },
  {
    github: 'maciej-kisiel',
    discord: '936242781733654588',
    memberOf: [ROLE_IDS.GO_SDK],
  },
  {
    github: 'macoughl',
    discord: '740279257548193803',
    memberOf: [ROLE_IDS.COMMUNITY_MANAGERS],
  },
  {
    github: 'maheshmurag',
    memberOf: [ROLE_IDS.MODERATORS],
  },
  {
    github: 'markpollack',
    memberOf: [ROLE_IDS.JAVA_SDK],
  },
  {
    github: 'marshallofsound',
    memberOf: [ROLE_IDS.MCPB_MAINTAINERS],
  },
  {
    github: 'mattzcarey',
    discord: '224878268275359744',
    memberOf: [ROLE_IDS.TYPESCRIPT_SDK, ROLE_IDS.TOOL_ANNOTATIONS_IG, ROLE_IDS.WG_IG_FACILITATORS],
  },
  {
    github: 'maxisbey',
    discord: '1404871241738748058',
    memberOf: [ROLE_IDS.PYTHON_SDK],
  },
  {
    github: 'michaelneale',
    memberOf: [ROLE_IDS.RUST_SDK],
  },
  {
    github: 'mikekistler',
    discord: '915345005982408754',
    memberOf: [ROLE_IDS.CSHARP_SDK, ROLE_IDS.CSHARP_SDK_ADMIN],
  },
  {
    github: 'movetz',
    discord: '1427569183427919906',
    memberOf: [ROLE_IDS.SWIFT_SDK],
  },
  {
    github: 'nbarbettini',
    discord: '784552628930478090',
    memberOf: [ROLE_IDS.WG_IG_FACILITATORS],
  },
  {
    github: 'nickcoai',
    discord: '1153783469860732968',
    firstName: 'Nick',
    lastName: 'Cooper',
    googleEmailPrefix: 'nickc',
    memberOf: [ROLE_IDS.CORE_MAINTAINERS, ROLE_IDS.SERVER_IDENTITY_WG],
  },
  {
    github: 'nicolas-grekas',
    memberOf: [ROLE_IDS.PHP_SDK],
  },
  {
    github: 'Nyholm',
    discord: '466593085984342016',
    memberOf: [ROLE_IDS.PHP_SDK],
  },
  {
    github: 'ochafik',
    discord: '1004897332069925024',
    memberOf: [
      ROLE_IDS.MCP_APPS_SDK,
      ROLE_IDS.PYTHON_SDK,
      ROLE_IDS.PYTHON_SDK_AUTH,
      ROLE_IDS.TYPESCRIPT_SDK,
      ROLE_IDS.TYPESCRIPT_SDK_AUTH,
    ],
  },
  {
    github: 'og-ant',
    memberOf: [ROLE_IDS.SECURITY_WG],
  },
  {
    github: 'olaservo',
    discord: '1079841769946095620',
    firstName: 'Ola',
    lastName: 'Hungerford',
    googleEmailPrefix: 'ola',
    memberOf: [
      ROLE_IDS.COMMUNITY_MANAGERS,
      ROLE_IDS.DOCS_MAINTAINERS,
      ROLE_IDS.INSPECTOR_MAINTAINERS,
      ROLE_IDS.MAINTAINERS,
      ROLE_IDS.MODERATORS,
      ROLE_IDS.REFERENCE_SERVERS_MAINTAINERS,
      ROLE_IDS.SKILLS_OVER_MCP_IG,
      ROLE_IDS.WORKING_GROUPS,
    ],
  },
  {
    github: 'Ololoshechkin',
    memberOf: [ROLE_IDS.KOTLIN_SDK],
  },
  {
    github: 'pcarleton',
    discord: '1354465170969067852',
    firstName: 'Paul',
    lastName: 'Carleton',
    googleEmailPrefix: 'paul',
    existingGWSUser: true,
    memberOf: [
      ROLE_IDS.CORE_MAINTAINERS,
      ROLE_IDS.DOCS_MAINTAINERS,
      ROLE_IDS.ADMINISTRATORS,
      ROLE_IDS.MODERATORS,
      ROLE_IDS.PYTHON_SDK,
      ROLE_IDS.PYTHON_SDK_AUTH,
      ROLE_IDS.TYPESCRIPT_SDK,
      ROLE_IDS.TYPESCRIPT_SDK_AUTH,
      ROLE_IDS.AUTH_MAINTAINERS,
    ],
  },
  {
    github: 'pederhp',
    discord: '166255967665651713',
    memberOf: [
      ROLE_IDS.COMMUNITY_MANAGERS,
      ROLE_IDS.MAINTAINERS,
      ROLE_IDS.FINANCIAL_SERVICES_IG,
      ROLE_IDS.MODERATORS,
      ROLE_IDS.SKILLS_OVER_MCP_IG,
    ],
  },
  {
    github: 'petery-ant',
    memberOf: [ROLE_IDS.SECURITY_WG],
  },
  {
    github: 'pja-ant',
    discord: '328628782497923072',
    firstName: 'Peter',
    lastName: 'Alexander',
    googleEmailPrefix: 'pja',
    existingGWSUser: true,
    memberOf: [
      ROLE_IDS.CORE_MAINTAINERS,
      ROLE_IDS.MAINTAINERS,
      ROLE_IDS.SKILLS_OVER_MCP_IG,
      ROLE_IDS.TRANSPORT_WG,
    ],
  },
  {
    github: 'pronskiy',
    memberOf: [ROLE_IDS.PHP_SDK],
  },
  {
    github: 'pwwpche',
    discord: '1226238847013228604',
    skipGoogleUserProvisioning: true,
    memberOf: [ROLE_IDS.CORE_MAINTAINERS],
  },
  {
    github: 'rdimitrov',
    email: 'radoslav@modelcontextprotocol.io',
    discord: '1088231882979815424',
    firstName: 'Radoslav',
    lastName: 'Dimitrov',
    googleEmailPrefix: 'radoslav',
    existingGWSUser: true,
    memberOf: [ROLE_IDS.MAINTAINERS, ROLE_IDS.REGISTRY_MAINTAINERS, ROLE_IDS.SKILLS_OVER_MCP_IG],
  },
  {
    github: 'rreichel3',
    discord: '1458485333757788273',
    memberOf: [ROLE_IDS.TOOL_ANNOTATIONS_IG, ROLE_IDS.WG_IG_FACILITATORS],
  },
  {
    github: 'sambhav',
    email: 'sambhavs.email@gmail.com',
    firstName: 'Sambhav',
    lastName: 'Kothari',
    googleEmailPrefix: 'sambhav',
    discord: '840109459212206090',
    memberOf: [ROLE_IDS.MAINTAINERS, ROLE_IDS.FINANCIAL_SERVICES_IG],
  },
  {
    github: 'SamMorrowDrums',
    email: 'sammorrowdrums@github.com',
    discord: '782948163694493696',
    memberOf: [
      ROLE_IDS.PRIMITIVE_GROUPING_IG,
      ROLE_IDS.SKILLS_OVER_MCP_IG,
      ROLE_IDS.TOOL_ANNOTATIONS_IG,
      ROLE_IDS.WG_IG_FACILITATORS,
    ],
  },
  {
    github: 'sdubov',
    memberOf: [ROLE_IDS.KOTLIN_SDK],
  },
  {
    github: 'soyuka',
    email: 'soyuka@gmail.com',
    discord: '249323948842418186',
    memberOf: [ROLE_IDS.PHP_SDK],
  },
  {
    github: 'stallent',
    discord: '1137898074086314136',
    memberOf: [ROLE_IDS.SWIFT_SDK],
  },
  {
    github: 'stephentoub',
    memberOf: [ROLE_IDS.CSHARP_SDK, ROLE_IDS.CSHARP_SDK_ADMIN],
  },
  {
    github: 'sunishsheth2009',
    discord: '1414713222224941097',
    memberOf: [ROLE_IDS.SKILLS_OVER_MCP_IG],
  },
  {
    github: 'tadasant',
    email: 'tadas@modelcontextprotocol.io',
    discord: '400092503677599754',
    firstName: 'Tadas',
    lastName: 'Antanavicius',
    googleEmailPrefix: 'tadas',
    existingGWSUser: true,
    memberOf: [
      ROLE_IDS.COMMUNITY_MANAGERS,
      ROLE_IDS.MODERATORS,
      ROLE_IDS.MAINTAINERS,
      ROLE_IDS.WORKING_GROUPS,
      ROLE_IDS.INTEREST_GROUPS,
      ROLE_IDS.REGISTRY_MAINTAINERS,
      ROLE_IDS.ADMINISTRATORS,
    ],
  },
  {
    github: 'tarekgh',
    memberOf: [ROLE_IDS.CSHARP_SDK],
  },
  {
    github: 'tiginamaria',
    memberOf: [ROLE_IDS.KOTLIN_SDK],
  },
  {
    github: 'toby',
    email: 'toby@modelcontextprotocol.io',
    discord: '560155411777323048',
    firstName: 'Toby',
    lastName: 'Padilla',
    googleEmailPrefix: 'toby',
    existingGWSUser: true,
    memberOf: [ROLE_IDS.MAINTAINERS, ROLE_IDS.REGISTRY_MAINTAINERS],
  },
  {
    github: 'topherbullock',
    discord: '1059910719124013168',
    memberOf: [ROLE_IDS.RUBY_SDK],
  },
  {
    github: 'tzolov',
    discord: '1097924660055777290',
    memberOf: [ROLE_IDS.DOCS_MAINTAINERS, ROLE_IDS.JAVA_SDK],
  },
  {
    email: 'adamj@anthropic.com',
    memberOf: [ROLE_IDS.CATCH_ALL],
  },
  {
    email: 'davidsp@anthropic.com',
    memberOf: [ROLE_IDS.ANTITRUST],
  },
  {
    email: 'mattsamuels@anthropic.com',
    memberOf: [ROLE_IDS.ANTITRUST],
  },
  {
    email: 'davideramian@anthropic.com',
    memberOf: [ROLE_IDS.ANTITRUST],
  },
] as const;
